### ISSUE TITLE
Вопрос: Диод Шоттки

### ISSUE THREAD

**Issue by heX16** [clunet/avr-dmbs-lib#1]
В [оригинальной схеме](https://raw.githubusercontent.com/ClusterM/clunet/master/images/sample-schematic.png) у Кластера, микроконтроллер к шине был подключен напрямую.

У вас стоит Диод Шоттки.
Можете подсказать зачем использован Диод Шоттки и почему в такой конфигурации? - Диод стоит против течения тока, то есть должен мешать прохождению сигнала, хотя я вижу что конкретно у этого номинала довольно сильный обратный ток в 1 мА.
Почему не использовать простое сопротивление?

P.S.: Прошу прощения если вопрос нубский - у меня мало опыта в схемотехнике, я ни разу не сталкивался с таким применением Диод Шоттки и не смог найти объяснение в интернете.

**Comment by dudanov** [comment]
Пин чтения подтянут к питанию МК внутренним сопротивлением. Диод Шоттки используется для согласования уровня напряжений CLUNET и микроконтроллера. Если уровни одинаковые, то можно и напрямую, но лучше с диодом, он защитит устройства в сети.

**Comment by heX16** [comment]
> Диод Шоттки используется для согласования уровня напряжений CLUNET и микроконтроллера. 

Понял! Благодаря включенному pull-up на пине образуются "родные" 5 вольт. Затем когда любой МК прижимает линию к 0, то подтяжка от МК утекает через диод на линию, и на пине образуется 0.

А обратный ток диода разве не "пропустит" на пин изначальное напряжение? - мне кажется что этих микроамперов вполне хватит для повышения напряжения (ему ведь там некуда деваться - стока нет). 

> но лучше с диодом, он защитит устройства в сети.

Защитит от чего? Защитит если на МК произойдет "неприятность" (ну например 24 вольта прилетит и его пробьет весь) ? Или защита от каких-то "паразитных" токов и наводок?


P.S. Спасибо за ответы! Изначально я подумал что диод установлен для защиты самого устройства, но теперь все понял.

**Comment by dudanov** [comment]
> Понял! Благодаря включенному pull-up на пине образуются "родные" 5 вольт. Затем когда любой МК прижимает линию к 0, то подтяжка от МК утекает через диод на линию, и на пине образуется 0.

Все верно

> А обратный ток диода разве не "пропустит" на пин изначальное напряжение? - мне кажется что этих микроамперов вполне хватит для повышения напряжения (ему ведь там некуда деваться - стока нет).

Обратный ток гораздо меньше тока через подтягивающий резистор. К тому же каждый пин МК защищен 2 защитными диодами на землю и напряжение питания.

> Защитит от чего? Защитит если на МК произойдет "неприятность" (ну например 24 вольта прилетит и его пробьет весь) ? Или защита от каких-то "паразитных" токов и наводок?

Защитит от замыкания шины CLUNET на шину питания. У себя использую еще 2 дополнительные защиты:

1. В каждом устройстве вывод транзистора подключаю к CLUNET через предохранитель PolySwitch на 100 мА.
2. Между CLUNET и землей поставил TVS диод SMBJ5.0A, который ограничивает напряжение на безопасном уровне.
